import pyautogui
import time
import os
import sys

def init():
    pyautogui.click(1917, 1070)
    time.sleep(2)
    pyautogui.doubleClick(46, 559)
    time.sleep(2)
    pyautogui.write('IMS')
    time.sleep(1)
    pyautogui.hotkey('enter')
    time.sleep(1)
    pyautogui.write('R325493')
    pyautogui.hotkey('tab')
    pyautogui.write('jan32246')
    pyautogui.hotkey('enter')
    time.sleep(1)
    pyautogui.write('02')
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.write('n')
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.write('4')
    pyautogui.hotkey('enter')
    time.sleep(3)
    pyautogui.write('4')
    pyautogui.hotkey('tab')
    pyautogui.write('elmbdz')
    pyautogui.hotkey('enter')
    pyautogui.hotkey('alt', 'tab')
    return 0

def nc():
    pyautogui.hotkey('alt', 'tab')
    pyautogui.hotkey('up')
    pyautogui.hotkey('tab')
    pyautogui.write(station)
    pyautogui.hotkey('enter')
    time.sleep(3)
    pyautogui.write(seq)
    pyautogui.hotkey('enter')
    time.sleep(4)
    pyautogui.hotkey('f5')
    pyautogui.write('nr33f')
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.write('r')
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.write('s')
    pyautogui.hotkey('enter')
    time.sleep(2)
    # pesquisa cliente
    pyautogui.hotkey('f4')
    time.sleep(2)
    pyautogui.hotkey('f8')
    time.sleep(2)
    pyautogui.hotkey('f8')
    time.sleep(2)
    pyautogui.hotkey('f8')
    time.sleep(2)
    pyautogui.hotkey('f8')
    time.sleep(2)
    pyautogui.write('2')
    pyautogui.hotkey('enter')
    time.sleep(2)
    # pesquisa insumo
    pyautogui.hotkey('f5')
    time.sleep(2)
    pyautogui.hotkey('tab')
    pyautogui.write('mo')
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.write('5')
    pyautogui.hotkey('enter')
    time.sleep(2)
    # preenche NC
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.write(insumo)
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.write(tipo_nc)
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.write(rg)
    pyautogui.write(disposicao)
    pyautogui.hotkey('enter')
    time.sleep(3)
    pyautogui.write('s')
    pyautogui.hotkey('enter')
    time.sleep(3)
    pyautogui.hotkey('enter')
    time.sleep(3)
    pyautogui.write('4')
    pyautogui.hotkey('enter')
    time.sleep(3)
    pyautogui.write('4')
    pyautogui.hotkey('tab')
    pyautogui.write('elmbdz')
    pyautogui.hotkey('enter')
    pyautogui.hotkey('alt', 'tab')
    return 0