import pyautogui
import time
import os
import sys
import clipboard
insumo='mão de obra para realizar manutencao preventiva'
tipo_nc='falta devido afastamento covid'
disposicao='reprogramar atividade'

def init(rg, senha):
    pyautogui.click(1917, 1070)
    time.sleep(2)
    pyautogui.doubleClick(46, 559)
    time.sleep(2)
    pyautogui.write('IMS')
    time.sleep(1)
    pyautogui.hotkey('enter')
    time.sleep(1)
    pyautogui.write(rg)
    pyautogui.hotkey('tab')
    pyautogui.write(senha)
    pyautogui.hotkey('enter')
    time.sleep(1)
    pyautogui.write('02')
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.write('n')
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.write('4')
    pyautogui.hotkey('enter')
    time.sleep(3)
    pyautogui.write('4')
    pyautogui.hotkey('tab')
    pyautogui.write('elmbdz')
    pyautogui.hotkey('enter')
    pyautogui.hotkey('alt', 'tab')
    return 0

def nc(station, rg):
    pyautogui.hotkey('alt', 'tab')
    time.sleep(2)
    pyautogui.hotkey('up')
    pyautogui.hotkey('tab')
    pyautogui.write(station)
    pyautogui.hotkey('enter')
    time.sleep(7)
    #copiar numero da os
    pyautogui.click(389, 355)
    pyautogui.doubleClick(389, 355)
    pyautogui.hotkey('ctrl', 'c')
    os = clipboard.paste()
    if not os.isspace():
        if os == '001 ':
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.write('1')
            pyautogui.hotkey('enter')
            pyautogui.hotkey('f5')
            pyautogui.write('nr33f')
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.write('r')
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.write('s')
            pyautogui.hotkey('enter')
            time.sleep(2)
            # pesquisa cliente
            pyautogui.hotkey('f4')
            time.sleep(2)
            pyautogui.hotkey('f8')
            time.sleep(2)
            pyautogui.hotkey('f8')
            time.sleep(2)
            pyautogui.hotkey('f8')
            time.sleep(2)
            pyautogui.hotkey('f8')
            time.sleep(2)
            pyautogui.write('2')
            pyautogui.hotkey('enter')
            time.sleep(2)
            # pesquisa insumo
            pyautogui.hotkey('f5')
            time.sleep(2)
            pyautogui.hotkey('tab')
            pyautogui.write('mo')
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.write('5')
            pyautogui.hotkey('enter')
            time.sleep(2)
            # preenche NC
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.write(insumo)
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.write(tipo_nc)
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.write(rg[1:6])
            pyautogui.write(disposicao)
            pyautogui.hotkey('enter')
            time.sleep(3)
            pyautogui.write('s')
            pyautogui.hotkey('enter')
            time.sleep(1)
            pyautogui.hotkey('enter')
            time.sleep(3)
            pyautogui.write('4')
            pyautogui.hotkey('enter')
            time.sleep(3)
            pyautogui.write('4')
            pyautogui.hotkey('tab')
            pyautogui.write('elmbdz')
            pyautogui.hotkey('enter')
            pyautogui.hotkey('alt', 'tab')
            return 0
        else:
            #fechar os
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.hotkey('tab')
            pyautogui.write('1')
            pyautogui.hotkey('enter')
            pyautogui.hotkey('f5')
            pyautogui.write('nr33f')
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.write('r') 
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.write('s')
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.hotkey('f10')
            time.sleep(1)
            pyautogui.write('02')
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.write('n')
            pyautogui.hotkey('enter')
            time.sleep(2)
            pyautogui.write('4')
            pyautogui.hotkey('enter')
            time.sleep(3)
            pyautogui.write('4')
            pyautogui.hotkey('tab')
            pyautogui.write('elmbdz')
            pyautogui.hotkey('enter')
            pyautogui.hotkey('alt', 'tab')
            return 0
        
        
        
    
